name: vyuh_feature_system
description: Provides the essential building blocks for a CMS-driven UI
version: 1.38.4
homepage: https://vyuh.tech
repository: https://github.com/vyuh-tech/vyuh/tree/main/packages/system/vyuh_feature_system
issue_tracker: https://github.com/vyuh-tech/vyuh/issues

topics:
  - vyuh
  - feature
  - system

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.16.0'

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.3.1
  cached_network_image_platform_interface: ^4.1.1
  collection: ^1.18.0
  flutter_mobx: ^2.2.0+2
  json_annotation: ^4.9.0
  mobx: ^2.3.0+1
  smooth_page_indicator: ^1.1.0
  flutter_animate: ^4.3.0
  logger: ^2.0.2+1
  go_router: ^15.1.1
  flutter_sanity_portable_text: ^1.6.2
  vyuh_core: ^1.44.1
  vyuh_extension_content: ^1.26.2
  json_path: ^0.7.1
  url_launcher: ^6.3.0
  nanoid: ^1.0.0
  video_player: ^2.9.1
  chewie: ^1.7.5
  flutter_inappwebview: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.6

flutter:
